### ISSUE TITLE
Project License

### ISSUE THREAD

**Issue by GhoulofGSG9** [KyleAbent/ns2siege#1]
This project can't be put under Mozilla Public License as it contains multiple fragments of code which fall under the copyright of different persons and companies and furthermore includes content which was published with licenses incompatible with the Mozilla Public License (e.g. the MIT License).

In conclusion I ask you politly to remove the Mozilla Public License from this project and make sure that people understand that it contains content which falls under the copyright of third parties.

**Comment by KyleAbent** [comment]
No idea which license to use. Had to choose one. Read as much as I could on
there and found the most reasonable one. I see and use github and im trying
to learn it. It's pretty complicated. I much prefer my own method but I
think the project can grow. But sure I can look at  the license but I still
have no idea which to put it under.

On Tue, Nov 10, 2015 at 1:21 PM, GhoulofGSG9 notifications@github.com
wrote:

> This project can't be put under Mozilla Public License as it contains
> multiple fragments of code which fall under the copyright of different
> persons and companies and furthermore includes content which was published
> with licenses incompatible with the Mozilla Public License (e.g. the MIT
> License).
> 
> In conclusion I ask you polity to remove the Mozilla Public License from
> this project and make sure that people understand that it contains content
> which falls under the copyright of third parties.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/KyleAbent/ns2siege/issues/1.

## 

www.youtube.com/rocksmithdiary
www.youtube.com/mynameiskyleabent
www.soundcloud.com/kyle-abent
www.facebook.com/kyle.abent
www.rocksmithdiary.blogspot.com
www.reddit.com/r/rocksmithcustomsongs
http://www.twitch.tv/kyleabent/
http://www.last.fm/user/kyleabent
kyleabent@gmail.com

**Comment by GhoulofGSG9** [comment]
I would to suggest to not use a license for now. In that case the project falls under your personal copyright.

The issue with licenses and NS2 mods is that UWE never published any kind of "Fair Usage" agreement which would allow you to license your work including code of them.

So you would have to remove all kind of UWE code to be able to apply a license onto this project.

**Comment by KyleAbent** [comment]
Ok sure. Deleted the license. My intention isn't to steal or take credit for anyone elses writing. I just like to combine everything into what I like to play and others come join me and contribute and play together. I also write alot in this process. =].

**Comment by GhoulofGSG9** [comment]
I made this issue ticket to make you aware of the issue of applying a license onto a NS2 mod.

Closed as it has been fixed with commit 8f6b9b2
